spikesorters/basesorter.py, spikesorters/mountainsort4/mountainsort4.py
=> Check parameters in base sorter 

.travis.yml, spikesorters/basesorter.py, spikesorters/mountainsort4/mountainsort4.py, spikesorters/spyking_circus/config_default.params, spikesorters/spyking_circus/spyking_circus.py, spikesorters/tests/common_tests.py, spikesorters/tests/test_spykingcircus.py, spikesorters/tests/test_tridesclous.py
- install mpich
- force SC==0.8.0
=> Enabled SC test on travis

.travis.yml, spikesorters/herdingspikes/herdingspikes.py, spikesorters/kilosort/kilosort.py, spikesorters/klusta/klusta.py, spikesorters/mountainsort4/mountainsort4.py, spikesorters/spyking_circus/spyking_circus.py
Forse string to Path object in `get_result_form_folder` function
=> Get result from folder fix

spikesorters/__init__.py, spikesorters/launcher.py, spikesorters/tests/test_launcher.py, spikesorters/tests/test_tridesclous.py
@alejoe91 @colehurwitz : are we agree on that ?
=> Move launcher from spiketoolkit.sorters to spikesorters.

spikesorters/ironclust/ironclust.py, spikesorters/ironclust/mdaio.py, spikesorters/ironclust/mdarecordingextractor2.py
I only added some comments for now (for fear of breaking something). In the future I will do a proper merge/cleanup with spikeextractors, but I am not ready yet.
=> some comments to ironclust wrapper

setup.py, spikesorters/basesorter.py, spikesorters/herdingspikes/herdingspikes.py, spikesorters/ironclust/ironclust.py, spikesorters/kilosort/kilosort.py, spikesorters/kilosort2/kilosort2.py, spikesorters/klusta/klusta.py, spikesorters/mountainsort4/mountainsort4.py, spikesorters/spyking_circus/spyking_circus.py, spikesorters/tests/common_tests.py, spikesorters/tridesclous/tridesclous.py
Remove cycli dep : add spiketoolkit as dep.
This must be merge when spiketoolkit will be released.
Accidentaly, this PR also include the versionning of sorters.
I am sorry. Would you be agree to merge everthing at once because I lost the branch ....
=> [WIP] Remove cycli dep : add spiketoolkit as dep

spikesorters/waveclus/waveclus.py
waveclus was failing because the write script was called without providing a file
=> Waveclus fix

spikesorters/tridesclous/tridesclous.py
Remove 'nb_max' from public parameters because must be set with auto method
=> Remove 'nb_max' from public parameters because must be set with auto method

spikesorters/basesorter.py, spikesorters/kilosort/kilosort.py, spikesorters/kilosort2/kilosort2.py, spikesorters/klusta/klusta.py, spikesorters/spyking_circus/spyking_circus.py, spikesorters/tests/common_tests.py, spikesorters/tridesclous/tridesclous.py
update to match this PR https://github.com/SpikeInterface/spikeextractors/pull/301
- add a WARNING if groups are present but gtouping_property is not used
- removed electrode_dimensions param (enforcing 2D positions)
=> Fixes for save_to_probe_file changes

spikesorters/ironclust/ironclust.py
@jamesjun I merged with master and made this new PR. This should pass all tests
=> IronClust default parameters changed

requirements_sorters.txt, spikesorters/spyking_circus/config_default.params, spikesorters/spyking_circus/spyking_circus.py
This one is for Samuel. Improvements in SC 0.8.7 with regularized templates and better fits (in theory). Note also that in the SpikeForest wrappers, I changed the default file format to raw binary, since with numpy, the code is not running for very large datasets. I guess this is because when creating a GroundTruth study object, the data file is copied, and not in a chunked manner with numpy, thus leading to memory issues
=> Updates for SC 0.8.7

spikesorters/kilosort2/kilosort2.py, spikesorters/kilosort2/kilosort2_config.m
https://github.com/SpikeInterface/spikesorters/issues/96
=> Exposed minfr_goodchannels param

.gitignore, requirements_sorters.txt, spikesorters/basesorter.py, spikesorters/herdingspikes/herdingspikes.py, spikesorters/ironclust/ironclust.py, spikesorters/kilosort/kilosort.py, spikesorters/kilosort2/kilosort2.py, spikesorters/launcher.py, spikesorters/mountainsort4/mountainsort4.py, spikesorters/sorter_tools.py, spikesorters/sorterlist.py, spikesorters/tests/test_ironclust.py, spikesorters/tests/test_kilosort.py, spikesorters/tests/test_kilosort2.py, spikesorters/tests/test_launcher.py, spikesorters/tests/test_sorterlist.py, spikesorters/tests/test_tridesclous.py, spikesorters/tests/test_waveclus.py, spikesorters/waveclus/waveclus.py
* Print sorters version.
* log in json format inside folder
* params in json format inside folder
=> Some improvement

requirements_sorters.txt, spikesorters/spyking_circus/config_default.params, spikesorters/spyking_circus/spyking_circus.py
We'll just release a new version of SC, that should give much better performance. There are minor changes in the default parameters
=> New default parameters for a better merging in 0.9.2

requirements_sorters.txt, spikesorters/ironclust/ironclust.py
I exposed four more parameters and changed default values for IronClust (v5.8.5).
=> ironclust default parameters updated (v5.8.5)

requirements_sorters.txt, spikesorters/spyking_circus/spyking_circus.py
Following the remarks made by Matthias, I've just released an incremental 0.9.5 version in order to speed up quite a lot the run time of SC. In theory, no major performance change should be observed, since everything is mostly about code refactoring. The run times with SpikeInterface are now much better, and I hope I won't have any more timeouts in SF.
=> Release 0.9.5 improving running times

requirements_sorters.txt
Sorry for the numerous PR, but I worked hard to speed up drastically SC, and now this starts to be pretty good. At least neuropixel is working fine on a laptop, with 4 cores and a limited amount of RAM
=> Update for 0.9.6

MANIFEST.in, requirements_sorters.txt, spikesorters/hdsort/__init__.py, spikesorters/hdsort/hdsort.py, spikesorters/hdsort/hdsort_config.m, spikesorters/hdsort/hdsort_master.m, spikesorters/ironclust/ironclust.py, spikesorters/kilosort/kilosort.py, spikesorters/kilosort2/kilosort2.py, spikesorters/sorterlist.py, spikesorters/utils/shellscript.py, spikesorters/waveclus/waveclus.py
- HDsort implementation
- fixed version check: if `win` in sys.platform includes `darwin`
=> Added HDSort and fixed platform on mac

spikesorters/basesorter.py, spikesorters/hdsort/hdsort.py, spikesorters/herdingspikes/herdingspikes.py, spikesorters/ironclust/ironclust.py, spikesorters/kilosort/kilosort.py, spikesorters/kilosort2/kilosort2.py, spikesorters/klusta/klusta.py, spikesorters/mountainsort4/mountainsort4.py, spikesorters/sorterlist.py, spikesorters/spyking_circus/spyking_circus.py, spikesorters/tridesclous/tridesclous.py, spikesorters/waveclus/waveclus.py
@alejoe91 removed gui params from spikesorters (will move to spikely)
=> removed gui params

spikesorters/launcher.py
@alejoe91 I need this to debug when a sorter bug distantly in run_sorters(...)
=> control in run_sorters(...) if raise_error when sorter.run()

spikesorters/basesorter.py
https://github.com/SpikeInterface/spikesorters/issues/131
=> Change tmp to output in output_folder name

spikesorters/basesorter.py
wrong call to new `set_channel_locations`
=> Fix dummy location creation

spikesorters/hdsort/hdsort.py, spikesorters/herdingspikes/herdingspikes.py, spikesorters/ironclust/ironclust.py, spikesorters/mountainsort4/mountainsort4.py, spikesorters/spyking_circus/spyking_circus.py, spikesorters/waveclus/waveclus.py
checks if recording are re-filtered by the sorter and prints a warning message
related to this as well https://github.com/SpikeInterface/spikesorters/pull/128
=> Check if recording is filtered and print warning if filter is true

spikesorters/launcher.py, spikesorters/tests/test_launcher.py
@alejoe91 @MarineChap
Hi,
I finally started it.
It is in fact super simple.
I will do an example.
#90
=> Proof of concept of dask client for run_sorters

spikesorters/hdsort/hdsort.py, spikesorters/ironclust/ironclust.py, spikesorters/kilosort/kilosort.py, spikesorters/kilosort2/kilosort2.py, spikesorters/klusta/klusta.py, spikesorters/spyking_circus/spyking_circus.py, spikesorters/waveclus/waveclus.py
https://github.com/SpikeInterface/spikesorters/issues/137
=> Add run_ to sorter scripts

spikesorters/kilosort2/kilosort2.py
it should be 'recording.dat', not 'recording'
=> not working, added four letters

spikesorters/basesorter.py, spikesorters/hdsort/hdsort.py, spikesorters/hdsort/hdsort_master.m, spikesorters/launcher.py, spikesorters/sorterlist.py
+ remove output folder if it exists before running a sorter
needs this [PR](https://github.com/SpikeInterface/spikeextractors/pull/408/files) to be merged.
=> Use HDSortSortingExtractor for HDsort 

spikesorters/basesorter.py, spikesorters/hdsort/hdsort.py, spikesorters/herdingspikes/herdingspikes.py, spikesorters/ironclust/ironclust.py, spikesorters/kilosort/kilosort.py, spikesorters/kilosort2/kilosort2.py, spikesorters/klusta/klusta.py, spikesorters/mountainsort4/mountainsort4.py, spikesorters/sorterlist.py, spikesorters/spyking_circus/spyking_circus.py, spikesorters/tests/test_launcher.py, spikesorters/tridesclous/tridesclous.py, spikesorters/waveclus/waveclus.py
- HS2:
- changed `detection_threshold` --> `detect_threshold`
- @mhhennig @colehurwitz can you fill in the last parameter descriptions?
- TDC:
- changed some parameters so that they are the same among sorters: `freq_min` / `freq_max` / 'detect_threshold` / `detect_sign`
- @samuelgarcia check params description
- Waveclus: @ferchaure can you fill in the last parameters and check that the ones I input are correct?
=> Added params and sorter descriptions for all sorters

requirements_sorters.txt, spikesorters/basesorter.py
SC tests are suddenly failing.
@yger can you check if they work locally for you with the latest master or this branch?
=> Re-insert SC tests

spikesorters/waveclus/waveclus.py
Hi Guys, one of the last commits broke the waveclus sorter.  This little change fixes it
=> fix renamed installed method on wc

setup.py, spikesorters/version.py
=> Updates for new release

MANIFEST.in, spikesorters/kilosort3/__init__.py, spikesorters/kilosort3/kilosort3.py, spikesorters/kilosort3/kilosort3_channelmap.m, spikesorters/kilosort3/kilosort3_config.m, spikesorters/kilosort3/kilosort3_master.m, spikesorters/sorterlist.py
Hey guys,
This adds an interface for Kilosort3. It was largely a copy-paste and edit job from the kilosort2.5 sorter with updates to the matlab scripts and slight parameter changes from those new matlab scripts that come with KS3. Not much of the core python code has been changed from 2.5 so please let me know if there are other changes to those that you would recommend.
I've tested it with a couple of recordings and so far it seems alright.
=> Add kilosort3 sorter

spikesorters/kilosort3/kilosort3.py
Issue [194](https://github.com/SpikeInterface/spikesorters/issues/194#issuecomment-775284182)
Replace KILOSORT_PATH by KILOSORT3_PATH at kilosort3.py
=> fix ks3 path

spikesorters/yass/yass.py
Turned off the flag that yass uses to generate phy data.
=> yass; set phy file flag to off

spikesorters/launcher.py, spikesorters/sorterlist.py
This is a quick PR to update the docstrings, in particular for `run_sorters` which seemed to have two groups of argument descriptions. This update merges them together. There are also minor updates and consistency updates in `sorter_list`.
=> DOC: Update docstrings
